"""Refactor relations

Revision ID: 1636e918583a
Revises: 824dd036de4a
Create Date: 2026-01-14 07:27:29.913122

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1636e918583a"
down_revision: Union[str, Sequence[str], None] = "824dd036de4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_class_association",
        sa.Column("student_id", sa.String(), nullable=False),
        sa.Column("class_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("student_id", "class_id"),
    )
    op.add_column("questions", sa.Column("test_id", sa.String(), nullable=True))
    op.create_foreign_key(None, "questions", "tests", ["test_id"], ["id"])
    op.drop_column("students", "class_id")
    op.drop_column("tests", "questions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tests",
        sa.Column(
            "questions",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "students",
        sa.Column("class_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_column("questions", "test_id")
    op.drop_table("student_class_association")
    # ### end Alembic commands ###
